### ISSUE TITLE
`git pw patch list` doesn't show all the patches

### ISSUE THREAD

**Issue by andy-shev** [getpatchwork/git-pw#34]
Instance: patchwork.kernel.org
Project: platform-driver-x86

For example, patches with the status "Superseded" or "Not Applicable" simple skipped. `pwclient` shows them correctly.

`git pw patch list --state superseded` shows them as well, but I want to have everything which is not archived to be shown by default.

**Comment by stephenfin** [comment]
Thanks again for the detailed bug report. This is intentional. We only list patches that are in `under-review` or `new` state:

https://github.com/getpatchwork/git-pw/blob/1.5.0/git_pw/patch.py#L186

This matches up with the states that have `action_required=True` in Patchwork:

https://github.com/getpatchwork/patchwork/blob/d6491b59d97ba7fd6a498490f4cb3b6159dd53ee/patchwork/fixtures/default_states.xml#L5-L14

We do this because we only want to show patches that we still need to do something with by default. If you wish to override this, you can do so by providing the `--state` argument.

    git-pw patch list --state under-review --state new --state superseded --state not-applicable

You could also alias this to use the flags by default or provide a [wrapper script](https://eklitzke.org/bash-subcommand-aliases). I guess we could also make this configurable via an environment option but I imagine this is a pretty niche use case. Because of the "nicheness" of the issue, I'm going to close this as `notabug`. Please re-open if this is a serious blocker though.

**Comment by andy-shev** [comment]
Good to know, thanks!
